### ISSUE TITLE
Add function to verify email

### ISSUE THREAD

**Issue by lablnet** [lablnet/Email-Spider#1]
Add function to`helper.py` that verify email address
by looking to `MXrecords`

**Comment by pedrogengo** [comment]
Hey, can I help on this issue? If yes, whats is and where can I find the MXrecords?

**Comment by lablnet** [comment]
> Hey, can I help on this issue? If yes, whats is and where can I find the MXrecords?

Look at here => https://stackoverflow.com/questions/1976712/using-mx-records-to-validate-email-addresses but its about PHP i want similar concept

**Comment by pedrogengo** [comment]
Ok! I was searching and find this [lib](https://pypi.org/project/email-validator/ ), which can be helpful to solve the problem. Can you assign to me this issue? Until the end of the week, I will make a PR to solve
